[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ingredient_parser"]

[project]
# Use a slightly different name to avoid conflict with pre-existing package in pypi
name = "ingredient_parser_nlp"
version = "0.1.0-alpha1"
authors = [
    { name="Tom Strange", email="tpstrange@gmail.com"},
]
description = "A Python package to parse structured information from recipe ingredient sentences"
readme = "README.md"
license = { file="LICENSE"}
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "nltk",
    "python-crfsuite",
    "typing-extensions",
]

[project.urls]
"HomePage" = "https://github.com/strangetom/ingredient-parser"


